package yerbie.client;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.concurrent.Executors;
import yerbie.autogenerated.YerbieAPI;
import yerbie.autogenerated.implementation.YerbieAPIImpl;
import yerbie.serde.DataTransformer;
import yerbie.serde.JobSpecTransformer;

public class ClientProvider {
  private static final String URL_FORMAT_STRING = "%s:%d";

  private final String host;
  private final int port;

  public ClientProvider(String host, int port) {
    this.host = host;
    this.port = port;
  }

  public YerbieClient initializeYerbieClient() {
    ObjectMapper objectMapper = new ObjectMapper();
    DataTransformer dataTransformer = new DataTransformer(objectMapper);
    JobSpecTransformer jobSpecTransformer = new JobSpecTransformer(objectMapper);

    return new YerbieClient(host, port, dataTransformer, jobSpecTransformer);
  }

  public YerbieConsumer initializeYerbieConsumer(String queue, JobRepository jobRepository) {
    YerbieAPI yerbieAPI = new YerbieAPIImpl(String.format(URL_FORMAT_STRING, host, port));
    ObjectMapper objectMapper = new ObjectMapper();
    DataTransformer dataTransformer = new DataTransformer(objectMapper);
    JobSpecTransformer jobSpecTransformer = new JobSpecTransformer(objectMapper);

    return new YerbieConsumer(
        Executors.newFixedThreadPool(10),
        yerbieAPI,
        queue,
        jobSpecTransformer,
        dataTransformer,
        jobRepository);
  }
}
