# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    tags:
      - "java/v*.*.*"
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v2.0.0
      with:
        java-version: '14'
        distribution: 'adopt'
    - name: Set up Node and Npm
      uses: actions/setup-node@v2
        with:
          node-version: '12'
    - run: npm install -g autorest
    - name: Publish artifact
      working-directory: ./yerbie-java
      env:
         GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

        # The GITHUB_REF tag comes in the format 'refs/tags/xxx'.
        # If we split on '/' and take the 3rd value,
        # we can get the release name.
      run: |
        NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f4)
        echo "New version: ${NEW_VERSION}"
        echo "Github username: ${GITHUB_ACTOR}"
        ./gradlew -Pversion=${NEW_VERSION} publish
      
